import type { NicheTheme } from './types'

export const APEX_GROOM: NicheTheme = {
  id: 'apex-groom',
  name: 'APEX GROOM',
  niche: "Men's Grooming",
  tagline: 'Engineered for the modern Indian man.',
  styleFamily: 'Bold',
  previewImage: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=80',
  previewImages: [
    'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=80',
    'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80',
    'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=80',
  ],
  accentHex: '#C26A3F',
  sectionCount: 80,
  colorSystem: {
    primary: '#C26A3F',
    primaryFg: '#FFFFFF',
    secondary: '#1A1A1A',
    secondaryFg: '#FFFFFF',
    accent: '#E8855E',
    background: '#F5F4F2',
    surface: '#FFFFFF',
    surfaceRaised: '#EDEBE8',
    border: '#D9D5CF',
    borderStrong: '#B8B0A6',
    text: '#1A1A1A',
    textMuted: '#6B6560',
    textInverse: '#FFFFFF',
    success: '#2D6A4F',
    warning: '#C26A3F',
    error: '#B91C1C',
  },
  typography: {
    displayFont: "'Anton', Impact, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    monoFont: "'JetBrains Mono', monospace",
    googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Anton&family=Inter:wght@400;500;600&display=swap',
    displayWeights: [400],
    bodyWeights: [400, 500, 600],
    scaleRatio: 1.25,
  },
  motionSystem: {
    defaultEasing: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    springEasing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    sharpEasing: 'cubic-bezier(0.12, 0, 0.39, 0)',
    fastDuration: '120ms',
    baseDuration: '250ms',
    slowDuration: '500ms',
  },
  pages: {
    home: {
      sections: [
        {
          id: 'ag-announce',
          type: 'announcementBar',
          label: 'Announcement',
          settings: {
            text: '⚡ Free shipping above ₹599 · Dermatologist tested · 30-day money-back guarantee',
            backgroundColor: '#1A1A1A',
            textColor: '#C26A3F',
          },
        },
        {
          id: 'ag-hero',
          type: 'heroBoldSplit',
          label: 'Hero',
          settings: {
            eyebrow: 'The Grooming System',
            headline: 'LOOK SHARP.\nSTAY SHARP.',
            subhead: 'Science-backed grooming formulated for Indian skin and climate. No fluff. No compromise.',
            primaryCtaLabel: 'Shop the System',
            primaryCtaUrl: '/collections/grooming-system',
            secondaryCtaLabel: 'Take the Quiz',
            secondaryCtaUrl: '/pages/quiz',
            imageUrl: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=1200&q=90',
            layout: 'media-left',
            backgroundColor: '#1A1A1A',
            textColor: '#FFFFFF',
          },
        },
        {
          id: 'ag-routine',
          type: 'routineQuiz',
          label: 'Routine Quiz',
          settings: {
            headline: 'Find your routine',
            subhead: '3 questions. Your perfect grooming system.',
            ctaLabel: 'Start the quiz',
          },
        },
        {
          id: 'ag-before-after',
          type: 'beforeAfterSlider',
          label: 'Before / After',
          settings: {
            headline: '30 days. Real results.',
            beforeLabel: 'Before',
            afterLabel: 'Week 4',
            beforeImage: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=80',
            afterImage: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=80',
          },
        },
        {
          id: 'ag-bestsellers',
          type: 'featuredCollection',
          label: 'Bestsellers',
          settings: {
            eyebrow: 'What Actually Works',
            title: 'The Bestsellers',
            collectionSlug: 'bestsellers',
            count: 4,
            ctaLabel: 'Shop all',
          },
        },
        {
          id: 'ag-ingredients',
          type: 'ingredientWall',
          label: 'Ingredients',
          settings: {
            headline: 'Every ingredient earns its place',
            ingredients: [
              { name: 'Niacinamide 10%', benefit: 'Reduces pigmentation and regulates sebum' },
              { name: 'Kojic Acid', benefit: 'Natural brightening without harsh bleaches' },
              { name: 'Hyaluronic Acid', benefit: '72-hour moisture lock for Indian humidity' },
              { name: 'Retinol 0.3%', benefit: 'Targets fine lines and uneven texture' },
            ],
          },
        },
        {
          id: 'ag-subscription',
          type: 'subscriptionTable',
          label: 'Subscription',
          settings: {
            headline: 'Subscribe & never run out',
            plans: [
              { name: 'Monthly', discount: '10%', label: 'Most Flexible' },
              { name: 'Quarterly', discount: '20%', label: 'Most Popular' },
              { name: 'Biannual', discount: '30%', label: 'Best Value' },
            ],
          },
        },
        {
          id: 'ag-testimonials',
          type: 'testimonialsBold',
          label: 'Testimonials',
          settings: {
            title: 'Real men. Real results.',
            reviews: [
              { name: 'Rahul M.', location: 'Pune', rating: 5, text: 'Switched from a pharmacy brand. Night and day difference. My face actually feels clean after the face wash.' },
              { name: 'Karan S.', location: 'Delhi', rating: 5, text: 'The beard serum is the real deal. No more dry flakes. My barber asked what I started using.' },
              { name: 'Vikram P.', location: 'Bengaluru', rating: 5, text: 'Used the 3-month kit. Sunscreen doesn\'t feel greasy for the first time in my life.' },
            ],
          },
        },
        {
          id: 'ag-footer',
          type: 'footerMinimal',
          label: 'Footer',
          settings: {
            storeName: 'APEX GROOM',
            tagline: 'Grooming engineered for the Indian man.',
            columns: [
              { title: 'Products', links: [{ label: 'Face Care', url: '/collections/face' }, { label: 'Beard', url: '/collections/beard' }, { label: 'Body', url: '/collections/body' }, { label: 'Bundles', url: '/collections/bundles' }] },
              { title: 'Learn', links: [{ label: 'Ingredient Index', url: '/pages/ingredients' }, { label: 'Skin Guide', url: '/pages/skin-guide' }, { label: 'Grooming Basics', url: '/pages/basics' }] },
              { title: 'Help', links: [{ label: 'FAQ', url: '/pages/faq' }, { label: 'Shipping', url: '/pages/shipping' }, { label: 'Returns', url: '/pages/returns' }, { label: 'Contact', url: '/pages/contact' }] },
            ],
          },
        },
      ],
    },
    product: {
      sections: [
        { id: 'agp-gallery', type: 'productGallery', label: 'Gallery', settings: { layout: 'filmstrip', showBeforeAfter: true } },
        { id: 'agp-buybox', type: 'stickyBuyBox', label: 'Buy Box', settings: { showEmi: false, showPincode: true, showCod: true, showSubscribeOption: true } },
        { id: 'agp-ingredients', type: 'ingredientList', label: 'Ingredients', settings: { showFullList: true, showPubmedLinks: true } },
        { id: 'agp-howto', type: 'howToUse', label: 'How to Use', settings: { style: 'steps' } },
        { id: 'agp-reviews', type: 'reviewsGrid', label: 'Reviews', settings: { showVerifiedBadge: true } },
        { id: 'agp-related', type: 'featuredCollection', label: 'Pair with', settings: { title: 'Complete your routine', count: 4 } },
      ],
    },
    collection: {
      sections: [
        { id: 'agc-header', type: 'collectionHeader', label: 'Header', settings: { style: 'bold' } },
        { id: 'agc-filters', type: 'collectionFilters', label: 'Filters', settings: { showSkinType: true, showConcern: true, showPrice: true } },
        { id: 'agc-grid', type: 'collectionGrid', label: 'Products', settings: { columns: 4, showQuickAdd: true } },
      ],
    },
    cart: {
      sections: [
        { id: 'agc-cart', type: 'cartDrawer', label: 'Cart', settings: { showSubscribeUpgrade: true, showFreeShippingBar: true, freeShippingThreshold: 599, showBundleSuggestion: true } },
      ],
    },
    about: {
      sections: [
        { id: 'aga-hero', type: 'heroBoldFull', label: 'Hero', settings: { headline: 'BUILT FOR THE MODERN INDIAN MAN', imageUrl: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=1400&q=90' } },
        { id: 'aga-story', type: 'founderStory', label: 'Founder Story', settings: { headline: 'Why we started', body: 'We were tired of buying products designed for European skin and Indian weather. APEX GROOM is built around Indian dermatology research, tested on Indian skin types, priced for the Indian middle class.' } },
      ],
    },
  },
  seedProducts: [
    {
      name: '10% Niacinamide Face Serum',
      slug: 'niacinamide-face-serum',
      description: 'Clinical-grade 10% Niacinamide + Zinc PCA. Reduces acne, dark spots, and oiliness in 4 weeks. Dermatologist tested for Indian skin.',
      price: 649,
      comparePrice: 899,
      images: ['https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=90'],
      tags: ['serum', 'niacinamide', 'face', 'acne', 'bestseller'],
      category: 'Face Care',
      hsnCode: '3304',
      gstRate: 18,
    },
    {
      name: 'Matte SPF 50 Sunscreen',
      slug: 'matte-spf50-sunscreen',
      description: 'PA+++ UVA/UVB protection with a matte, non-greasy finish. No white cast. Built for Indian summers.',
      price: 399,
      images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=90'],
      tags: ['sunscreen', 'spf50', 'matte', 'face'],
      category: 'Face Care',
      hsnCode: '3304',
      gstRate: 18,
    },
    {
      name: 'Beard Growth & Nourish Oil',
      slug: 'beard-growth-oil',
      description: 'Bhringraj and castor oil blend that stimulates follicles and eliminates beard dandruff. 4-week visible thickness guarantee.',
      price: 549,
      comparePrice: 699,
      images: ['https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=90'],
      tags: ['beard', 'hair-growth', 'oil', 'grooming'],
      category: 'Beard',
      hsnCode: '3305',
      gstRate: 18,
    },
    {
      name: 'Complete Grooming Kit',
      slug: 'complete-grooming-kit',
      description: 'Face wash, toner, serum, moisturiser, and sunscreen — the full 5-step routine in one box. 30-day starter set.',
      price: 1499,
      comparePrice: 2194,
      images: ['https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=90'],
      tags: ['kit', 'bundle', 'starter', 'routine'],
      category: 'Bundles',
      hsnCode: '3304',
      gstRate: 18,
    },
  ],
  seedCollections: [
    { name: 'Grooming System', slug: 'grooming-system', description: 'The complete daily routine.', image: 'https://images.unsplash.com/photo-1585747860715-2ba37e788b70?w=800&q=90' },
    { name: 'Face Care', slug: 'face', description: 'Serums, moisturisers, and sunscreen.', image: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=90' },
    { name: 'Beard', slug: 'beard', description: 'Oils, balms, and washes.', image: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=800&q=90' },
    { name: 'Bestsellers', slug: 'bestsellers', description: 'What Indian men are buying.', image: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=90' },
    { name: 'Bundles', slug: 'bundles', description: 'Save more, groom better.', image: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=90' },
    { name: 'New Arrivals', slug: 'new', description: 'Latest drops.', image: 'https://images.unsplash.com/photo-1621605815971-fbc98d665033?w=800&q=90' },
  ],
}
