import type { NicheTheme } from './types'

export const AURENE: NicheTheme = {
  id: 'aurene',
  name: 'AURENE',
  niche: 'Luxury Jewellery',
  tagline: 'Crafted to be inherited.',
  styleFamily: 'Luxe',
  previewImage: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80',
  previewImages: [
    'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80',
    'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80',
    'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80',
  ],
  accentHex: '#B08D57',
  sectionCount: 80,
  colorSystem: {
    primary: '#B08D57',
    primaryFg: '#FAF6F1',
    secondary: '#1A1A1A',
    secondaryFg: '#FAF6F1',
    accent: '#8B6914',
    background: '#FAF6F1',
    surface: '#FFFFFF',
    surfaceRaised: '#F5F0EB',
    border: '#E8DDD0',
    borderStrong: '#C9B99A',
    text: '#1A1A1A',
    textMuted: '#8B7355',
    textInverse: '#FAF6F1',
    success: '#2D6A4F',
    warning: '#B08D57',
    error: '#9B2335',
  },
  typography: {
    displayFont: "'Cormorant Garamond', Georgia, serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    monoFont: "'JetBrains Mono', monospace",
    googleFontsUrl: 'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,600;1,300;1,400&family=Inter:wght@400;500;600&display=swap',
    displayWeights: [300, 400, 600],
    bodyWeights: [400, 500, 600],
    scaleRatio: 1.333,
  },
  motionSystem: {
    defaultEasing: 'cubic-bezier(0.25, 0.46, 0.45, 0.94)',
    springEasing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    sharpEasing: 'cubic-bezier(0.12, 0, 0.39, 0)',
    fastDuration: '150ms',
    baseDuration: '400ms',
    slowDuration: '800ms',
  },
  pages: {
    home: {
      sections: [
        {
          id: 'a-announce',
          type: 'announcementBar',
          label: 'Announcement',
          settings: {
            text: '✦ Free express shipping on orders above ₹5,000 · BIS Hallmarked · Lifetime Exchange',
            backgroundColor: '#1A1A1A',
            textColor: '#B08D57',
          },
        },
        {
          id: 'a-hero',
          type: 'heroEditorialSplit',
          label: 'Hero Banner',
          settings: {
            eyebrow: 'Heirloom Collection 2026',
            headline: 'Crafted to be\ninherited.',
            subhead: 'Solid gold. Hand-finished by master craftsmen in Jaipur. Every piece carries a lineage.',
            primaryCtaLabel: 'Shop the Collection',
            primaryCtaUrl: '/collections/heirloom',
            secondaryCtaLabel: 'Our Craft',
            secondaryCtaUrl: '/pages/craft',
            imageUrl: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=1200&q=90',
            layout: 'media-right',
            backgroundColor: '#FAF6F1',
          },
        },
        {
          id: 'a-press',
          type: 'pressBand',
          label: 'Press',
          settings: {
            title: 'As seen in',
            logos: ['Vogue India', 'Harper\'s Bazaar', 'Elle India', 'Femina', 'The Hindu'],
          },
        },
        {
          id: 'a-craft',
          type: 'craftStory',
          label: 'Craft Story',
          settings: {
            eyebrow: 'The Atelier',
            headline: 'Where gold meets generations of craft',
            body: 'Every AURENE piece begins as a sketch in our Jaipur studio, passes through the hands of third-generation karigars, and emerges with BIS hallmark certification. No shortcuts. No compromises.',
            imageUrl: 'https://images.unsplash.com/photo-1584302179602-e4c3d3fd629d?w=1200&q=90',
            stat1Value: '75+',
            stat1Label: 'Years of craft',
            stat2Value: '100%',
            stat2Label: 'BIS Hallmarked',
            stat3Value: '12,000+',
            stat3Label: 'Happy families',
          },
        },
        {
          id: 'a-collection',
          type: 'featuredCollection',
          label: 'Featured Collection',
          settings: {
            eyebrow: 'New Arrivals',
            title: 'The Heirloom Collection',
            collectionSlug: 'heirloom',
            count: 4,
            ctaLabel: 'View all pieces',
          },
        },
        {
          id: 'a-categories',
          type: 'categoryGrid',
          label: 'Category Grid',
          settings: {
            title: 'Shop by Occasion',
            columns: 4,
            categories: [
              { label: 'Wedding', image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80' },
              { label: 'Engagement', image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=600&q=80' },
              { label: 'Festive', image: 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=80' },
              { label: 'Everyday', image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80' },
            ],
          },
        },
        {
          id: 'a-testimonials',
          type: 'testimonialsLuxe',
          label: 'Testimonials',
          settings: {
            title: 'What our families say',
            reviews: [
              { name: 'Priya Sharma', location: 'Mumbai', rating: 5, text: 'I wore my AURENE necklace on my wedding day. Three months later, my sister wore it at hers. That is exactly what heirloom means.' },
              { name: 'Meera Nair', location: 'Bengaluru', rating: 5, text: 'The craftsmanship is unlike anything I have seen at this price. My grandmother actually asked where I got it.' },
              { name: 'Anjali Gupta', location: 'Delhi', rating: 5, text: 'Lifetime exchange policy sealed the deal. But the piece itself made me forget I ever needed reassurance.' },
            ],
          },
        },
        {
          id: 'a-emi',
          type: 'emiStrip',
          label: 'EMI Strip',
          settings: {
            text: 'No-cost EMI starting ₹833/month · Available on HDFC, ICICI, Bajaj Finserv, and more',
            backgroundColor: '#FAF6F1',
            borderColor: '#E8DDD0',
          },
        },
        {
          id: 'a-newsletter',
          type: 'newsletter',
          label: 'Newsletter',
          settings: {
            eyebrow: 'The Inner Circle',
            headline: 'First access to new drops. Invitations to private previews. Stories from the atelier.',
            placeholder: 'Your email address',
            ctaLabel: 'Join the circle',
            backgroundColor: '#1A1A1A',
            textColor: '#FAF6F1',
          },
        },
        {
          id: 'a-footer',
          type: 'footerFull',
          label: 'Footer',
          settings: {
            storeName: 'AURENE',
            tagline: 'Heirloom jewellery, handcrafted in Jaipur since 1952.',
            columns: [
              { title: 'Shop', links: [{ label: 'New Arrivals', url: '/collections/new' }, { label: 'Wedding', url: '/collections/wedding' }, { label: 'Engagement', url: '/collections/engagement' }, { label: 'Festive', url: '/collections/festive' }] },
              { title: 'Our Story', links: [{ label: 'The Craft', url: '/pages/craft' }, { label: 'BIS Certification', url: '/pages/bis' }, { label: 'Sustainability', url: '/pages/sustainability' }] },
              { title: 'Help', links: [{ label: 'Shipping & Delivery', url: '/pages/shipping' }, { label: 'Returns & Exchange', url: '/pages/returns' }, { label: 'Ring Sizing', url: '/pages/ring-sizing' }, { label: 'Contact Us', url: '/pages/contact' }] },
            ],
            showPaymentBadges: true,
            showBisBadge: true,
            showGstNumber: true,
          },
        },
      ],
    },
    product: {
      sections: [
        { id: 'ap-gallery', type: 'productGallery', label: 'Gallery', settings: { layout: 'grid', showZoom: true, show360: true } },
        { id: 'ap-buybox', type: 'stickyBuyBox', label: 'Buy Box', settings: { showEmi: true, showPincode: true, showCod: true, showWishlist: true, showShareButton: true } },
        { id: 'ap-details', type: 'productDetails', label: 'Details', settings: { showHsnCode: true, showWeight: true, showPurity: true, showCertification: true } },
        { id: 'ap-emi-calc', type: 'emiCalculator', label: 'EMI Calculator', settings: {} },
        { id: 'ap-reviews', type: 'reviewsGrid', label: 'Reviews', settings: { showVerifiedBadge: true, showPhotos: true } },
        { id: 'ap-related', type: 'featuredCollection', label: 'You may also like', settings: { title: 'Complete the look', count: 4 } },
      ],
    },
    collection: {
      sections: [
        { id: 'ac-header', type: 'collectionHeader', label: 'Header', settings: { showDescription: true, showImage: true } },
        { id: 'ac-filters', type: 'collectionFilters', label: 'Filters', settings: { showPurity: true, showOccasion: true, showPrice: true, showMetal: true } },
        { id: 'ac-grid', type: 'collectionGrid', label: 'Products', settings: { columns: 3, showQuickView: true, showWishlist: true } },
      ],
    },
    cart: {
      sections: [
        { id: 'ac-cart', type: 'cartDrawer', label: 'Cart', settings: { showEmi: true, showGiftWrap: true, showGstInvoice: true, showFreeShippingBar: true, freeShippingThreshold: 5000 } },
      ],
    },
    about: {
      sections: [
        { id: 'aa-hero', type: 'heroFullBleed', label: 'Hero', settings: { headline: 'Seventy years of unbroken craft', imageUrl: 'https://images.unsplash.com/photo-1584302179602-e4c3d3fd629d?w=1400&q=90' } },
        { id: 'aa-story', type: 'craftStory', label: 'Story', settings: { headline: 'From a small Jaipur workshop to 12,000 families', body: 'AURENE began in 1952 when Ramchand Singhania set up a one-room workshop in the Pink City\'s jewellery quarter. Today, his granddaughter leads a team of 47 karigars — but the hands-on craft has never changed.' } },
      ],
    },
  },
  seedProducts: [
    {
      name: 'Heirloom Solitaire Ring',
      slug: 'heirloom-solitaire-ring',
      description: 'A 0.5ct VS1 round brilliant diamond, set in hand-polished 22K gold. The prong setting is designed to hold the stone for generations.',
      price: 89000,
      comparePrice: 105000,
      images: ['https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=90', 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&q=90'],
      tags: ['ring', 'diamond', 'solitaire', 'wedding', '22k-gold'],
      category: 'Rings',
      hsnCode: '7113',
      gstRate: 3,
    },
    {
      name: 'Polki Kundan Necklace',
      slug: 'polki-kundan-necklace',
      description: 'Hand-set Polki diamonds in 24K gold foil Kundan work. A Jaipur tradition, now certified BIS. Comes with authentication card.',
      price: 145000,
      images: ['https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=90'],
      tags: ['necklace', 'polki', 'kundan', 'bridal', 'jaipur'],
      category: 'Necklaces',
      hsnCode: '7113',
      gstRate: 3,
    },
    {
      name: 'Temple Jhumki Earrings',
      slug: 'temple-jhumki-earrings',
      description: 'South Indian temple jewellery motifs in 22K gold. Each earring is hand-embossed with Lakshmi figures by our senior karigar.',
      price: 34500,
      images: ['https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=90'],
      tags: ['earrings', 'temple', 'jhumki', 'south-indian', '22k'],
      category: 'Earrings',
      hsnCode: '7113',
      gstRate: 3,
    },
    {
      name: 'Gold Mangalsutra',
      slug: 'gold-mangalsutra',
      description: 'A modern take on the traditional mangalsutra. 18K gold beads with a contemporary pendant. Wearable every day.',
      price: 28000,
      images: ['https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=90'],
      tags: ['mangalsutra', 'wedding', '18k', 'daily-wear'],
      category: 'Mangalsutra',
      hsnCode: '7113',
      gstRate: 3,
    },
  ],
  seedCollections: [
    { name: 'Heirloom Collection', slug: 'heirloom', description: 'Pieces made to be passed down.', image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=90' },
    { name: 'Wedding Edit', slug: 'wedding', description: 'Bridal jewellery for the most important day.', image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=90' },
    { name: 'Everyday Gold', slug: 'everyday', description: 'Lightweight gold for daily wear.', image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=90' },
    { name: 'Festive', slug: 'festive', description: 'Statement pieces for celebrations.', image: 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=90' },
    { name: 'New Arrivals', slug: 'new', description: 'Fresh from the Jaipur atelier.', image: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800&q=90' },
    { name: 'Engagement', slug: 'engagement', description: 'Rings and sets for the proposal.', image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=90' },
  ],
}
